version: '3.8'
services:
  exampleapi:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.docker
    container_name: exampleapi
    image: example/api
    #volumenes para que se actualice en tiempo real, el que no esta bindeado es para que no se instalen los modulos en el contenedor
    volumes:
      - /api/node_modules
      - ./:/api
    restart: always
    mem_limit: 512m
    #puerto externo:puerto interno
    ports:
      - '2525:2222'
    depends_on:
      - exampledb
    command: ['npm', 'run', 'start:dev']
    links:
      - exampledb
    networks:
      - example-net

  exampledb:
    image: mysql:5.7
    container_name: exampledb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: example
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - example-net

  adminer:
    image: adminer
    container_name: exampleadminer
    restart: always
    ports:
      - 8585:8080
    links:
      - exampledb
    networks:
      - example-net
    depends_on:
      - exampledb

networks:
  example-net:
    driver: bridge
    external: true
